export const routes = {
  HOME: '/',
  SIGN_OUT: '/sign-out',
  SIGN_IN: '/sign-in',
  ABOUT: '/about',
  DO_NOT_SELL: '/about/do-not-sell',
  PRIVACY: '/about/privacy',
  TERMS_OF_USE: '/about/terms-of-use',
  PUBLIC_TEMPALTES: '/templates',
  ACCOUNT: '/account',
  INBOX: '/account/inbox',
  ORGANIZATIONS: '/account/organizations',
  USER_SETTINGS: '/account/settings',
  DASHBOARD: (hashid: string) => `/org/${hashid}`,
  COMPONENTS: (hashid: string) => `/org/${hashid}/components`,
  DOMAINS: (hashid: string) => `/org/${hashid}/domains`,
  TEMPLATES: (hashid: string) => `/org/${hashid}/templates`,
  USERS: (hashid: string) => `/org/${hashid}/users`,
  SETTINGS: (hashid: string) => `/org/${hashid}/settings`,
  ROLES: (hashid: string) => `/org/${hashid}/settings/roles`,
  INVITE: (hashid: string, token: string) => `/org/${hashid}/invite/${token}`,
  INVITE_EXPIRED: (hashid: string) => `/org/${hashid}/invite/expired`,
  ERROR: '/404',
};
